### ISSUE TITLE
Error with example from Getting Started

### ISSUE THREAD

**Issue by wires** [kettanaito/atomic-layout#175] opened 2019-05-25 17:07 UTC
## What:

I am getting different unexpected behaviours depending on the order in which the `areas*` attributes are specified and which names occur in them.

## Why:

No clue, should I be using a different `atomic-layout` version? Is the getting started guide outdated?

## Environment:

- node version: `11.7.0`
- npm version: `6.9.0`
- atomic-layout version: `0.8.0`

## Steps to reproduce:

Steps to reproduce the behavior.

Consider the following program (slightly adapted from https://redd.gitbook.io/atomic-layout/general/getting-started/workflow by adding `areasSm` explicitly).

```js
let areas = `
header
content
aside
footer
`

let areasMobile = `
header
content
aside
footer
`

let areasTablet = `
header header
content aside
footer footer
`

import {Composition} from 'atomic-layout';

const Page = () => (
    <Composition
        areas={areas}
        areasMd={areasTablet}
        areasSm={areasMobile}
    >{({ Header, Content, Aside, Footer }) => (
            <>
                <Header>Header</Header>
                <Content>Content</Content>
                <Aside>Aside</Aside>
                <Footer>Footer</Footer>
            </>
        )}
    </Composition>
)
```

If I remove `aside` from `areasMobile`, I get the following issue in the console:

```
react.development.js:88 Uncaught Invariant Violation: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
    at invariant (http://localhost:1234/main.65f60760.js:26042:19)
    at resolveDispatcher (http://localhost:1234/main.65f60760.js:27427:32)
    at Object.useMemo (http://localhost:1234/main.65f60760.js:27481:24)
    at MediaQuery (http://localhost:1234/main.65f60760.js:56027:41)
    at renderWithHooks (http://localhost:1234/main.65f60760.js:16822:22)
    at mountIndeterminateComponent (http://localhost:1234/main.65f60760.js:18978:17)
    at beginWork (http://localhost:1234/main.65f60760.js:19611:20)
    at performUnitOfWork (http://localhost:1234/main.65f60760.js:23652:16)
    at workLoop (http://localhost:1234/main.65f60760.js:23693:28)
    at HTMLUnknownElement.callCallback (http://localhost:1234/main.65f60760.js:3520:18)
```

## Expected behavior:

Do not show the `aside` component on a small screen.

**Comment by kettanaito** [comment] 2019-05-25 18:16
Hello, @wires. Thank you for reporting the issue. I will set up this scenario on local and debug it to find out what causes the problem. This issue will updated once I have technical analyzis.

**Comment by kettanaito** [comment] 2019-05-25 19:50
I couldn't reproduce this issue on the same release of `atomic-layout`. There are several strategies to proceed on this issue.

## Check `react` and `react-dom` versions

Based on the exception message, let's start by checking the versions of `react` and `react-dom` packages in your application:

```bash
grep react package.json
```

Running the command above in your project's directory should produce a similar result:

```
"react": "^16.8.6",
"react-dom": "^16.8.6",
```

In case the versions of these packages differ, please install them the way your app would use the same versions.

## Check reproduction scenario

Could you please see if it works for you on `hooks-call-error` branch of this repo? This would mean:

1. Clone the repo
1. Install its dependencies (`yarn install`)
1. Run Storybook (`yarn storybook`)
1. Open "Bugfixes > Hooks error" story

---

Please let me know if it would be still reproducible. Thanks.

**Comment by wires** [comment] 2019-05-28 14:55
I have exactly those react versions ; will try out your reproduction scenario and report back.

**Comment by wires** [comment] 2019-05-28 17:28
I did as you said and hereby confirm the "Bugfixes > Hooks error" story seems to work:

![atomic-layout-storybook](https://user-images.githubusercontent.com/315734/58498596-a6741a80-817e-11e9-95c1-2981128e41ef.gif)

The error in the console appears as the storybook sidebar disappears and seems unrelated

**Comment by wires** [comment] 2019-05-28 17:42
That is strange, I started a new project from scratch and did not have an issue, besides #173.
https://gist.github.com/wires/be37707ded21ece11383c0afbd18492f

![atomic-layout-test](https://user-images.githubusercontent.com/315734/58499514-a07f3900-8180-11e9-9739-7de996e8a481.gif)

**Comment by kettanaito** [comment] 2019-05-28 18:59
@wires neat pick on the story book error 👍 

Layout options exception should be fixed, but perhaps I forgot to issue a patch release. Will do right now. I'm glad that the issue is resolved. My bet would be on react and react-dom versions mismatch for whatever reason. If hooks usage is improper it would fail a significant portion of the CI and be spotted.

Please let me know in case you experience anything else unexpected, or feel that some aspects need more guidance. I'm always eager to help. You rock.

**Closed by kettanaito** 2019-05-28 18:59 UTC
Labels: bug, possibly obsolete
