### ISSUE TITLE
Responsive props suffixes ignore casing (templateLg = templatelg)

### ISSUE THREAD

**Issue by dandelionadia** [kettanaito/atomic-layout#296] opened 2020-02-06 10:30 UTC
```
const templateMd = `
	contacts products links
	newsletter newsletter newsletter
	legal legal legal
`
const templateDesktop = `
contacts products links newsletter
legal legal legal legal
`
<Composition
      template={templateMobile}
      templateMd={templateMd}
      templatelg={templateDesktop}
 >...</Composition>
```

![image](https://user-images.githubusercontent.com/33199975/73928827-0efdc480-48d4-11ea-8931-aa37e7c16388.png)

**Comment by kettanaito** [comment] 2020-02-06 10:52
Thanks for reporting this, @dandelionadia. This doesn't seem right.

I think that the `parsePropName` function that breaks down a proper name into pure prop name, breakpoint, and behavior, explicitly has `i` set in its regular expression, which tells it to ignore the difference in casing:

https://github.com/kettanaito/atomic-layout/blob/64b10a5fa369a5432722f267c7ba091e86204d53/packages/atomic-layout-core/src/utils/strings/parsePropName/parsePropName.ts#L32

## Solution

1. Create a unit test for `parsePropName` to ensure it ignores breakpoint suffixes written in lowecase.
1. Remove the `i` regular expression flag.
1. It would be nice to display a developmeny-only warning for cases like this. Whenever you have `templatelg` Atomic Layout should recognize you have a breakpoint suffixes _in a wrong casing_, and warn you "did you mean `templateLg`?". Such warning should be produced in development only.

**Comment by kettanaito** [comment] 2020-04-01 08:17
I've finally got to tackling this. The fix will be released in the nearest time.

Please note that if you have any responsive props with lowercase breakpoint/behavior (by mistake, I suppose), those will stop work since the next release, and you would have to **rewrite them to contain capitalized breakpoint/behavior**.

**Closed** 2020-04-01 14:31 UTC
Labels: bug, good first issue, priority:medium, scope:calculation

**Comment by kettanaito** [comment] 2020-04-01 14:36
The issue is fixed and published:

```
 - @atomic-layout/emotion@0.13.0
 - atomic-layout@0.14.0
```

Please update and let me know in case you experience any problems. Thanks.
